[NOD-549] Add versioning support
kaspanet/faucet pull request #3
Opened 2020-01-05 15:36 UTC by svarogg

2020-01-05 16:39 UTC, someone235 requested changes

2020-01-05 16:39 UTC, someone235 commented on main.go
> +const appName = "faucet"
Where is it used?

2020-01-05 16:39 UTC, someone235 commented on main.go
> +		_, err = fmt.Fprintf(os.Stderr, "%s\n", err.Error())
You can use Fprintln

2020-01-07 14:48 UTC, someone235 approved these changes

2020-01-08 10:13 UTC, stasatdaglabs approved these changes

2020-01-08 10:13 UTC, merged